### ISSUE TITLE
Regex does not work in datasource

### ISSUE THREAD

**Issue by manueligno78** [jakubplichta/grafana-dashboard-builder#147]
Seems that regex is ignored for datasource template generation.

**Comment by manueligno78** [comment]
`---
- name: test Official Dashboards
  project:
    dashboard-prefix: test
    component:
      - frontend
      - backend
    env:
      - production:
          nodes: node3
    dashboards:
      - test Home

- name: test Home
  dashboard:
    title: 'Home'
    tags:
      - test
      - qos
    templates:
    - datasource-template:
        name: datasource
        query: 'prometheus'
        regex: '/^prod/'
    rows:
    - row:
        panels:
        - single-stat:
            span: 2
            title: Total PromHttp Requests
            datasource: $datasource
            targets:
            - prometheus-target:
                expr: "sum(promhttp_metric_handler_requests_total)"`

Produce that:
`{
  "nav": [
    {
      "type": "timepicker"
    }
  ],
  "rows": [
    {
      "collapse": false,
      "height": "250px",
      "panels": [
        {
          "colors": [
            "rgba(50, 172, 45, 0.97)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(245, 54, 54, 0.9)"
          ],
          "datasource": "$datasource",
          "nullPointMode": "null",
          "span": 2,
          "targets": [
            {
              "expr": "sum(promhttp_metric_handler_requests_total)"
            }
          ],
          "title": "Total PromHttp Requests",
          "type": "singlestat",
          "valueName": "current"
        }
      ],
      "showTitle": false,
      "title": ""
    }
  ],
  "tags": [
    "test",
    "qos"
  ],
  "templating": {
    "enable": true,
    "list": [
      {
        "name": "datasource",
        "query": "prometheus",
        "type": "datasource"
      }
    ]
  },
  "title": "Home"
}`

As you can see, regex is not present after parsing

**Comment by manueligno78** [comment]
Sorry, my fault. I forgot to rebuild, I was using an old version (built some month ago)

**Comment by jakubplichta** [comment]
@manueligno78 ok, good to hear.. sorry it took me so long to react
