### ISSUE TITLE
Why is sudo pip install needed?

### ISSUE THREAD

**Issue by dnck** [jakubplichta/grafana-dashboard-builder#192]
I found this project and it looks awesome! It does what I need it to do. 

Normally, I would just install something in a venv, but in the README here, it says to use sudo pip install. 

Googling for sudo pip install, the first link I find is, [is-sudo-pip-install-still-a-broken-practic?](https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice) from askubuntu. The first answer seems scary enough: 

> When you run pip with sudo, you run setup.py with sudo. In other words, you run arbitrary Python code from the Internet as root. If someone puts up a malicious project on PyPI and you install it, you give an attacker root access to your machine. 

I suppose sudo is needed here because of some authentication mechanisms within the project, perhaps they're needed when uploading dashboards? I'm not sure. 

Anyway, I was hoping for an explanation somewhere, since for me, working in a corporate setting, I can't just use it. Can someone explain why sudo pip install is needed? And if there are ways around doing so?

**Comment by jakubplichta** [comment]
@dnck thank you! I apologize about my reaction time. Yes, you are correct and `sudo` should not be needed.
