### ISSUE TITLE
config and connection to grafana

### ISSUE THREAD

**Issue by athingisathing** [jakubplichta/grafana-dashboard-builder#65]
I would like to see an example of how to connect to my grafana instance.

can you please add an example config.yaml to the project and readme.

**Comment by jakubplichta** [comment]
@athingisathing I'm on it. Sorry I haven't done it in the first place.

**Comment by athingisathing** [comment]
THANKS!

I tried honestly :)

Also does this neeeeedd ES running?

**Comment by jakubplichta** [comment]
Unfortunately only ES based store is currently supported as Grafana 1.x didn't have any reasonable API. 

It shouldn't be that hard to add support for 2.x API. Please create feature request for it and hopefully I'll get it done soon ;)

**Comment by jakubplichta** [comment]
@athingisathing FYI I just implemented support for Grafana API #80 and released it as 0.1.0a13 . Feel free to test it.
