### ISSUE TITLE
can we consume metrics from influxdb or other sources

### ISSUE THREAD

**Issue by Azulinho** [jakubplichta/grafana-dashboard-builder#81]
I am using grafana with influxdb, and I am wondering if I can use your code to query influxdb and build my dashboards.

does it support more fancy queries like:
dsType: influxdb
'select this and that' ?

**Comment by jakubplichta** [comment]
Hey, thanks for your interest. I've already thought about this and problem is that Grafana influxdb definition structure is not (well) documented and it will require more complex changes to builder structure. But it is definitely something I'd like to add.

**Comment by Azulinho** [comment]
okay,

I have wrapped up some ugly yaml to json with the bits I need for influxdb.
will have a proper dig through your code to see if I can add the missing
bits and submit a PR.

**Comment by greenscar** [comment]
I love the yaml formatting. +1 on influxdb support

**Comment by jakubplichta** [comment]
@ondrejFuchs unfortunately that's the current state of this project. It is something I'd like to address next but I cannot promise any due date.

**Comment by jakubplichta** [comment]
I've finally managed to update target system and it is possible to use InfluxDB raw queries.
