### ISSUE TITLE
Table panel

### ISSUE THREAD

**Issue by Isma399** [jakubplichta/grafana-dashboard-builder#88]
Hello,
can you add support for table panel?
We use it at work to show switch interface traffic.

Thanks

**Comment by Isma399** [comment]
```
panels:
  - title: Panel Title
    error: false
    span: 12
    editable: true
    type: table
    isNew: true
    id: 1
    styles:
    - type: date
      pattern: Time
      dateFormat: YYYY-MM-DD HH:mm:ss
    - unit: percent
      type: number
      decimals: 2
      colors:
      - rgba(245, 54, 54, 0.9)
      - rgba(237, 129, 40, 0.89)
      - rgba(50, 172, 45, 0.97)
      colorMode: 
      pattern: "/.*/"
      thresholds: []
    targets:
    - refId: A
      target: aliasByNode(highestAverage(c3750.traffic.perfdata.*.outUsage.value,
        5), 3)
    transform: timeseries_aggregations
    pageSize: 
    showHeader: true
    columns:
    - text: Avg
      value: avg
    - text: Max
      value: max
    scroll: true
    fontSize: 100%
    sort:
      col: 0
      desc: true
```

**Comment by Isma399** [comment]
Hello,
that works for me : 
`class Table(PanelsItemBase):
    def gen_json_from_data(self, data, context):
        panel_json = super(Table, self).gen_json_from_data(data, context)
        panel_json.update({
            'type': 'table',
            'title': data.get('title', None),
            'span': data.get('span', None),
            'transform': data.get('transform', None),
            'columns': data.get('columns', None)
        })
                
        targets = self.data.get('targets', [])
        if 'target' in self.data:
            targets.append(self.data['target'])
        panel_json['targets'] = map(lambda v: {'target': v}, targets)
               
        if 'style' in self.data:
            panel_json['styles'] =  self.data['style']

        return panel_json
            
`

**Comment by jakubplichta** [comment]
@Isma399 I've just merged support for table panel and will release it soon. Please review that everything works as expected. Thanks!
