### ISSUE TITLE
Support for regex in Template query

### ISSUE THREAD

**Issue by pcerny** [jakubplichta/grafana-dashboard-builder#94]
Grafana has an regex option to filter out values for given variable.
graphite value: site.cluster.node.prefix-value-suffix.subvalue
Example setup for prefix-value-suffix:
* variable name - var1
* values query - $site.$cluster.$node.prefix-*
* values regex - /prefix-(\w+)-suffix/

json output:
"type": "query",
"datasource": null,
"refresh_on_load": false,
"name": "var1",
"query": "$site.$cluster.$node.prefix-*",
"regex": "/prefix-(\w+)-suffix/"

**Comment by jakubplichta** [comment]
resolved by #96
